apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "mongodb.fullname" . }}
  labels:
    app: {{ template "mongodb.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "mongodb.fullname" . }}
    spec:
      containers:
      - name: {{ template "mongodb.fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        ports:
        - name: mongodb
          containerPort: 27017
        lifecycle:
          preStop:
            exec:
              command: ["gosu","mongodb","mongod","--shutdown"]
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /data/db
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        {{- if .Values.persistence.gcePersistentDisk }}
        gcePersistentDisk:
          pdName: {{ .Values.persistence.gcePersistentDisk | quote }}
          fsType: "ext4"
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ template "mongodb.fullname" . }}
        {{- end -}}
      {{- else }}
        emptyDir: {}
      {{- end -}}
