apiVersion: v1
kind: Service
metadata:
  name: {{ template "proxy.fullname" . }}
  labels:
    app: {{ template "proxy.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  {{ if .Values.proxy.serviceType }}
  type: {{ .Values.proxy.serviceType }}
  {{ end }}
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    stolon-proxy: "true"
    stolon-cluster: {{ .Values.clusterName }}
