apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "sentinel.fullname" . }}
  labels:
    app: {{ template "sentinel.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.sentinel.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "sentinel.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        stolon-cluster: {{ .Values.clusterName | quote }}
        stolon-sentinel: "true"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "sentinel.fullname" . }}
                - key: stolon-cluster
                  operator: In
                  values:
                  - {{ .Values.clusterName | quote }}
              topologyKey: kubernetes.io/hostname
      containers:
      - name: stolon-sentinel
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        command:
          - "/bin/bash"
          - "-ec"
          - |
            exec gosu stolon stolon-sentinel
        env:
          - name: STSENTINEL_CLUSTER_NAME
            value: {{ .Values.clusterName | quote}}
          - name: STSENTINEL_STORE_BACKEND
            value: {{ .Values.store.backend | quote}}
          - name: STSENTINEL_STORE_ENDPOINTS
            value: {{ template "store.endpoint" . }}
          - name: STSENTINEL_DEBUG
            value: {{ .Values.debug | quote}}
        resources:
{{ toYaml .Values.keeper.resources | indent 10 }}
