apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "mongo.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "mongo.fullname" . }}
data:
  mongod.conf: |
{{ toYaml .Values.configmap | indent 4 }}
