apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: {{ template "etcd.fullname" . }}
  {{- template "etcd.labels" . }}
spec:
  ports:
  - port: {{ .Values.peerPort }}
    name: peer
  - port: {{ .Values.clientPort }}
    name: client
  clusterIP: None
  selector:
    release: {{ .Release.Name | quote }}
    component: {{ .Values.component | quote }}
