apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: {{ template "etcd.fullname" . }}
  {{- template "etcd.labels" . }}
spec:
  ports:
  - port: {{ .Values.peerPort }}
    name: peer
  - port: {{ .Values.clientPort }}
    name: client
  clusterIP: None
  selector:
    release: {{ .Release.Name | quote }}
    component: {{ .Values.component | quote }}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "etcd.fullname" . }}
  {{- template "etcd.labels" . }}
spec:
  serviceName: {{ template "etcd.fullname" . }}
  replicas: {{ default 3 .Values.replicas }}
  template:
    metadata:
      name: {{ template "etcd.fullname" . }}
      {{- include "etcd.labels" . | indent 4 }}
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
      - name: {{ template "etcd.fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        ports:
        - containerPort: {{ .Values.peerPort }}
          name: peer
        - containerPort: {{ .Values.clientPort }}
          name: client
        resources:
          requests:
            cpu: "{{ .Values.cpu }}"
            memory: "{{ .Values.memory }}"
        env:
        - name: INITIAL_CLUSTER_SIZE
          value: {{ default 3 .Values.replicas | quote }}
        - name: SET_NAME
          value: {{ template "etcd.fullname" . }}
        volumeMounts:
        - name: datadir
          mountPath: /var/run/etcd
        lifecycle:
          preStop:
            exec:
              command:
                - "/bin/sh"
                - "-ec"
                - |
{{ .Files.Get "scripts/preStop.sh" | indent 18 }}
        command:
          - "/bin/sh"
          - "-ec"
          - |
{{ .Files.Get "scripts/command.sh" | indent 12 }}
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          # upstream recommended max is 700M
          storage: "{{ .Values.storage }}"
