apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: {{ template "redis-ha.service" . }}
  {{- include "redis-ha.labels" . | indent 2 }}
spec:
  ports:
  - port: {{ default 6379 .Values.server.port }}
    name: server
  - port: {{ default 26379 .Values.sentinel.port }}
    name: sentinel
  clusterIP: None
  selector:
    app: {{ template "redis-ha.app" . }}
