# Default values for Stolon Helm Chart.
# This is a YAML-formatted file.
## Declare variables to be passed into your templates.

## Override the name of the Chart.
##
# nameOverride:

## Stolon image.
##

image: "sorintlab/stolon"

## Stolon image version.
## ref: https://hub.docker.com/r/sorintlab/stolon/tags/
##
imageTag: "v0.7.0-pg9.6"

## Specify a imagePullPolicy: 'Always' if imageTag is 'latest', else set to 'IfNotPresent'.
## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# imagePullPolicy:

## Configuration values for Stolon.

clusterName: "kube-stolon"
debug: false


store:
  ##  Backend could be one of the following:
  ## - etcd
  ## - consul (not supported yet)
  backend: "etcd"

etcd:
  ## use etcd as backend
  enabled: true
  ## use existing etcd.(turn above false.)
  # service:

sentinel:
  replicas: 3
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"

proxy:
  replicas: 3
  ## Set serviceType to nodePort if needed
  ## proxy is used to route RW requests to the master
  # serviceType: NodePort

  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"

keeper:
  replicas: 3

  pgReplUsername: "repluser"
  pgReplPassword: "replPassword"
  pgSuperuserName: "stolon"
  ## set password for the superuser
  ## default is 15 random chars
  # pgSuperuserPasword: ""

  ## Set serviceType to nodePort if needed
  ## keeper service is used to route RO requests to all nodes
  # serviceType: NodePort

  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"

## Persistent Volume Storage configuration.
## ref: https://kubernetes.io/docs/user-guide/persistent-volumes
##

persistence:
  ## Enable persistence using Persistent Volume Claims.
  ##
  enabled: false

  ## Persistent Volume Storage Class.
  ## Leave it empty to use default storage class of the cluster
  ## Set it "-" to disable automatic storage provisioning
  ## class:

  ## Persistent Volume Access Mode.
  ##
  accessMode: ReadWriteOnce

  ## Persistent Volume Storage Size.
  ##
  size: 10Gi
